#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
if [[ "$STAGED_GO_FILES" = "" ]]; then
    echo "no go files were stashed"
    exit 0
fi
echo "found some interesting files!"
exit 1