#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

# first try and use lint to fix issues
go run github.com/golangci/golangci-lint/cmd/golangci-lint run --fix
if [[ $? == 1 ]]; then
  printf "COMMIT FAILED\n"
  exit 1
fi

# if it is still not good, then fail the commit.
go run github.com/golangci/golangci-lint/cmd/golangci-lint run
if [[ $? == 1 ]]; then
  printf "COMMIT FAILED\n"
  exit 1
fi

printf "COMMIT SUCCEEDED\n"
exit 0
