// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: nitric/proto/kvstore/v1/kvstore.proto

package kvstorepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KvStoreClient is the client API for KvStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvStoreClient interface {
	// Get an existing value
	GetKey(ctx context.Context, in *KvStoreGetKeyRequest, opts ...grpc.CallOption) (*KvStoreGetKeyResponse, error)
	// Create a new or overwrite an existing value
	SetKey(ctx context.Context, in *KvStoreSetKeyRequest, opts ...grpc.CallOption) (*KvStoreSetKeyResponse, error)
	// Delete a key and its value
	DeleteKey(ctx context.Context, in *KvStoreDeleteKeyRequest, opts ...grpc.CallOption) (*KvStoreDeleteKeyResponse, error)
	// Iterate over all keys in a store
	GetKeys(ctx context.Context, in *KvStoreGetKeysRequest, opts ...grpc.CallOption) (KvStore_GetKeysClient, error)
}

type kvStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKvStoreClient(cc grpc.ClientConnInterface) KvStoreClient {
	return &kvStoreClient{cc}
}

func (c *kvStoreClient) GetKey(ctx context.Context, in *KvStoreGetKeyRequest, opts ...grpc.CallOption) (*KvStoreGetKeyResponse, error) {
	out := new(KvStoreGetKeyResponse)
	err := c.cc.Invoke(ctx, "/nitric.proto.kvstore.v1.KvStore/GetKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) SetKey(ctx context.Context, in *KvStoreSetKeyRequest, opts ...grpc.CallOption) (*KvStoreSetKeyResponse, error) {
	out := new(KvStoreSetKeyResponse)
	err := c.cc.Invoke(ctx, "/nitric.proto.kvstore.v1.KvStore/SetKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) DeleteKey(ctx context.Context, in *KvStoreDeleteKeyRequest, opts ...grpc.CallOption) (*KvStoreDeleteKeyResponse, error) {
	out := new(KvStoreDeleteKeyResponse)
	err := c.cc.Invoke(ctx, "/nitric.proto.kvstore.v1.KvStore/DeleteKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) GetKeys(ctx context.Context, in *KvStoreGetKeysRequest, opts ...grpc.CallOption) (KvStore_GetKeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &KvStore_ServiceDesc.Streams[0], "/nitric.proto.kvstore.v1.KvStore/GetKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvStoreGetKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KvStore_GetKeysClient interface {
	Recv() (*KvStoreGetKeysResponse, error)
	grpc.ClientStream
}

type kvStoreGetKeysClient struct {
	grpc.ClientStream
}

func (x *kvStoreGetKeysClient) Recv() (*KvStoreGetKeysResponse, error) {
	m := new(KvStoreGetKeysResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KvStoreServer is the server API for KvStore service.
// All implementations should embed UnimplementedKvStoreServer
// for forward compatibility
type KvStoreServer interface {
	// Get an existing value
	GetKey(context.Context, *KvStoreGetKeyRequest) (*KvStoreGetKeyResponse, error)
	// Create a new or overwrite an existing value
	SetKey(context.Context, *KvStoreSetKeyRequest) (*KvStoreSetKeyResponse, error)
	// Delete a key and its value
	DeleteKey(context.Context, *KvStoreDeleteKeyRequest) (*KvStoreDeleteKeyResponse, error)
	// Iterate over all keys in a store
	GetKeys(*KvStoreGetKeysRequest, KvStore_GetKeysServer) error
}

// UnimplementedKvStoreServer should be embedded to have forward compatible implementations.
type UnimplementedKvStoreServer struct {
}

func (UnimplementedKvStoreServer) GetKey(context.Context, *KvStoreGetKeyRequest) (*KvStoreGetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKvStoreServer) SetKey(context.Context, *KvStoreSetKeyRequest) (*KvStoreSetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKey not implemented")
}
func (UnimplementedKvStoreServer) DeleteKey(context.Context, *KvStoreDeleteKeyRequest) (*KvStoreDeleteKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedKvStoreServer) GetKeys(*KvStoreGetKeysRequest, KvStore_GetKeysServer) error {
	return status.Errorf(codes.Unimplemented, "method GetKeys not implemented")
}

// UnsafeKvStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvStoreServer will
// result in compilation errors.
type UnsafeKvStoreServer interface {
	mustEmbedUnimplementedKvStoreServer()
}

func RegisterKvStoreServer(s grpc.ServiceRegistrar, srv KvStoreServer) {
	s.RegisterService(&KvStore_ServiceDesc, srv)
}

func _KvStore_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvStoreGetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nitric.proto.kvstore.v1.KvStore/GetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).GetKey(ctx, req.(*KvStoreGetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_SetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvStoreSetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).SetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nitric.proto.kvstore.v1.KvStore/SetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).SetKey(ctx, req.(*KvStoreSetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvStoreDeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nitric.proto.kvstore.v1.KvStore/DeleteKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).DeleteKey(ctx, req.(*KvStoreDeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_GetKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KvStoreGetKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvStoreServer).GetKeys(m, &kvStoreGetKeysServer{stream})
}

type KvStore_GetKeysServer interface {
	Send(*KvStoreGetKeysResponse) error
	grpc.ServerStream
}

type kvStoreGetKeysServer struct {
	grpc.ServerStream
}

func (x *kvStoreGetKeysServer) Send(m *KvStoreGetKeysResponse) error {
	return x.ServerStream.SendMsg(m)
}

// KvStore_ServiceDesc is the grpc.ServiceDesc for KvStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KvStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nitric.proto.kvstore.v1.KvStore",
	HandlerType: (*KvStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _KvStore_GetKey_Handler,
		},
		{
			MethodName: "SetKey",
			Handler:    _KvStore_SetKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _KvStore_DeleteKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetKeys",
			Handler:       _KvStore_GetKeys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nitric/proto/kvstore/v1/kvstore.proto",
}
