// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: nitric/proto/kvstore/v1/kvstore.proto

package kvstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provides a Key/Value Store
type Store struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The store name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Store) Reset() {
	*x = Store{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ValueRef provides a unique identifier for a value
type ValueRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key/value store name
	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	// The item's unique key within the store
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ValueRef) Reset() {
	*x = ValueRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRef) ProtoMessage() {}

func (x *ValueRef) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRef.ProtoReflect.Descriptor instead.
func (*ValueRef) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *ValueRef) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ValueRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Value provides a return value type
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ValueRef of the key/value pair, which includes the store and key
	Ref *ValueRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// The content (JSON object)
	Content *structpb.Struct `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetRef() *ValueRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Value) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

type KvStoreGetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ValueRef of the key/value pair to get, which includes the store and key
	Ref *ValueRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *KvStoreGetValueRequest) Reset() {
	*x = KvStoreGetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreGetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreGetValueRequest) ProtoMessage() {}

func (x *KvStoreGetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreGetValueRequest.ProtoReflect.Descriptor instead.
func (*KvStoreGetValueRequest) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *KvStoreGetValueRequest) GetRef() *ValueRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type KvStoreGetValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The retrieved value
	Value *Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KvStoreGetValueResponse) Reset() {
	*x = KvStoreGetValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreGetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreGetValueResponse) ProtoMessage() {}

func (x *KvStoreGetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreGetValueResponse.ProtoReflect.Descriptor instead.
func (*KvStoreGetValueResponse) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *KvStoreGetValueResponse) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type KvStoreSetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ValueRef of the key/value pair to set, which includes the store and key
	Ref *ValueRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// The value content to store (JSON object)
	Content *structpb.Struct `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *KvStoreSetValueRequest) Reset() {
	*x = KvStoreSetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreSetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreSetValueRequest) ProtoMessage() {}

func (x *KvStoreSetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreSetValueRequest.ProtoReflect.Descriptor instead.
func (*KvStoreSetValueRequest) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *KvStoreSetValueRequest) GetRef() *ValueRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *KvStoreSetValueRequest) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

type KvStoreSetValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KvStoreSetValueResponse) Reset() {
	*x = KvStoreSetValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreSetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreSetValueResponse) ProtoMessage() {}

func (x *KvStoreSetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreSetValueResponse.ProtoReflect.Descriptor instead.
func (*KvStoreSetValueResponse) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{6}
}

type KvStoreDeleteKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ValueRef of the key/value pair to delete, which includes the store and key
	Ref *ValueRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *KvStoreDeleteKeyRequest) Reset() {
	*x = KvStoreDeleteKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreDeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreDeleteKeyRequest) ProtoMessage() {}

func (x *KvStoreDeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreDeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*KvStoreDeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *KvStoreDeleteKeyRequest) GetRef() *ValueRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type KvStoreDeleteKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KvStoreDeleteKeyResponse) Reset() {
	*x = KvStoreDeleteKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreDeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreDeleteKeyResponse) ProtoMessage() {}

func (x *KvStoreDeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreDeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*KvStoreDeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{8}
}

type KvStoreScanKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The store to iterate over
	Store *Store `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	// The prefix to filter keys by
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *KvStoreScanKeysRequest) Reset() {
	*x = KvStoreScanKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreScanKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreScanKeysRequest) ProtoMessage() {}

func (x *KvStoreScanKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreScanKeysRequest.ProtoReflect.Descriptor instead.
func (*KvStoreScanKeysRequest) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *KvStoreScanKeysRequest) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *KvStoreScanKeysRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type KvStoreScanKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key of the key/value pair
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KvStoreScanKeysResponse) Reset() {
	*x = KvStoreScanKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvStoreScanKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvStoreScanKeysResponse) ProtoMessage() {}

func (x *KvStoreScanKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvStoreScanKeysResponse.ProtoReflect.Descriptor instead.
func (*KvStoreScanKeysResponse) Descriptor() ([]byte, []int) {
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{10}
}

func (x *KvStoreScanKeysResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_nitric_proto_kvstore_v1_kvstore_proto protoreflect.FileDescriptor

var file_nitric_proto_kvstore_v1_kvstore_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b,
	0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b,
	0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x6f, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x33, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x31, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x4d, 0x0a, 0x16, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x03, 0x72, 0x65,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22,
	0x4f, 0x0a, 0x17, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x69, 0x74, 0x72,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x80, 0x01, 0x0a, 0x16, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x03, 0x72,
	0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66,
	0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4e,
	0x0a, 0x17, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x1a,
	0x0a, 0x18, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x66, 0x0a, 0x16, 0x4b, 0x76,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x22, 0x2b, 0x0a, 0x17, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x63, 0x61,
	0x6e, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32,
	0xca, 0x03, 0x0a, 0x07, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x6d, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x08, 0x53, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x30, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x08, 0x53,
	0x63, 0x61, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x2f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x4b, 0x65, 0x79,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x4b, 0x65,
	0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0xa4, 0x01, 0x0a,
	0x1a, 0x69, 0x6f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x4b, 0x76, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a, 0x40, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0xaa,
	0x02, 0x17, 0x4e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b,
	0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0xca, 0x02, 0x17, 0x4e, 0x69, 0x74, 0x72,
	0x69, 0x63, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x5c, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nitric_proto_kvstore_v1_kvstore_proto_rawDescOnce sync.Once
	file_nitric_proto_kvstore_v1_kvstore_proto_rawDescData = file_nitric_proto_kvstore_v1_kvstore_proto_rawDesc
)

func file_nitric_proto_kvstore_v1_kvstore_proto_rawDescGZIP() []byte {
	file_nitric_proto_kvstore_v1_kvstore_proto_rawDescOnce.Do(func() {
		file_nitric_proto_kvstore_v1_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(file_nitric_proto_kvstore_v1_kvstore_proto_rawDescData)
	})
	return file_nitric_proto_kvstore_v1_kvstore_proto_rawDescData
}

var file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nitric_proto_kvstore_v1_kvstore_proto_goTypes = []interface{}{
	(*Store)(nil),                    // 0: nitric.proto.kvstore.v1.Store
	(*ValueRef)(nil),                 // 1: nitric.proto.kvstore.v1.ValueRef
	(*Value)(nil),                    // 2: nitric.proto.kvstore.v1.Value
	(*KvStoreGetValueRequest)(nil),   // 3: nitric.proto.kvstore.v1.KvStoreGetValueRequest
	(*KvStoreGetValueResponse)(nil),  // 4: nitric.proto.kvstore.v1.KvStoreGetValueResponse
	(*KvStoreSetValueRequest)(nil),   // 5: nitric.proto.kvstore.v1.KvStoreSetValueRequest
	(*KvStoreSetValueResponse)(nil),  // 6: nitric.proto.kvstore.v1.KvStoreSetValueResponse
	(*KvStoreDeleteKeyRequest)(nil),  // 7: nitric.proto.kvstore.v1.KvStoreDeleteKeyRequest
	(*KvStoreDeleteKeyResponse)(nil), // 8: nitric.proto.kvstore.v1.KvStoreDeleteKeyResponse
	(*KvStoreScanKeysRequest)(nil),   // 9: nitric.proto.kvstore.v1.KvStoreScanKeysRequest
	(*KvStoreScanKeysResponse)(nil),  // 10: nitric.proto.kvstore.v1.KvStoreScanKeysResponse
	(*structpb.Struct)(nil),          // 11: google.protobuf.Struct
}
var file_nitric_proto_kvstore_v1_kvstore_proto_depIdxs = []int32{
	1,  // 0: nitric.proto.kvstore.v1.Value.ref:type_name -> nitric.proto.kvstore.v1.ValueRef
	11, // 1: nitric.proto.kvstore.v1.Value.content:type_name -> google.protobuf.Struct
	1,  // 2: nitric.proto.kvstore.v1.KvStoreGetValueRequest.ref:type_name -> nitric.proto.kvstore.v1.ValueRef
	2,  // 3: nitric.proto.kvstore.v1.KvStoreGetValueResponse.value:type_name -> nitric.proto.kvstore.v1.Value
	1,  // 4: nitric.proto.kvstore.v1.KvStoreSetValueRequest.ref:type_name -> nitric.proto.kvstore.v1.ValueRef
	11, // 5: nitric.proto.kvstore.v1.KvStoreSetValueRequest.content:type_name -> google.protobuf.Struct
	1,  // 6: nitric.proto.kvstore.v1.KvStoreDeleteKeyRequest.ref:type_name -> nitric.proto.kvstore.v1.ValueRef
	0,  // 7: nitric.proto.kvstore.v1.KvStoreScanKeysRequest.store:type_name -> nitric.proto.kvstore.v1.Store
	3,  // 8: nitric.proto.kvstore.v1.KvStore.GetValue:input_type -> nitric.proto.kvstore.v1.KvStoreGetValueRequest
	5,  // 9: nitric.proto.kvstore.v1.KvStore.SetValue:input_type -> nitric.proto.kvstore.v1.KvStoreSetValueRequest
	7,  // 10: nitric.proto.kvstore.v1.KvStore.DeleteKey:input_type -> nitric.proto.kvstore.v1.KvStoreDeleteKeyRequest
	9,  // 11: nitric.proto.kvstore.v1.KvStore.ScanKeys:input_type -> nitric.proto.kvstore.v1.KvStoreScanKeysRequest
	4,  // 12: nitric.proto.kvstore.v1.KvStore.GetValue:output_type -> nitric.proto.kvstore.v1.KvStoreGetValueResponse
	6,  // 13: nitric.proto.kvstore.v1.KvStore.SetValue:output_type -> nitric.proto.kvstore.v1.KvStoreSetValueResponse
	8,  // 14: nitric.proto.kvstore.v1.KvStore.DeleteKey:output_type -> nitric.proto.kvstore.v1.KvStoreDeleteKeyResponse
	10, // 15: nitric.proto.kvstore.v1.KvStore.ScanKeys:output_type -> nitric.proto.kvstore.v1.KvStoreScanKeysResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_nitric_proto_kvstore_v1_kvstore_proto_init() }
func file_nitric_proto_kvstore_v1_kvstore_proto_init() {
	if File_nitric_proto_kvstore_v1_kvstore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Store); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreGetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreGetValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreSetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreSetValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreDeleteKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreDeleteKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreScanKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvStoreScanKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nitric_proto_kvstore_v1_kvstore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nitric_proto_kvstore_v1_kvstore_proto_goTypes,
		DependencyIndexes: file_nitric_proto_kvstore_v1_kvstore_proto_depIdxs,
		MessageInfos:      file_nitric_proto_kvstore_v1_kvstore_proto_msgTypes,
	}.Build()
	File_nitric_proto_kvstore_v1_kvstore_proto = out.File
	file_nitric_proto_kvstore_v1_kvstore_proto_rawDesc = nil
	file_nitric_proto_kvstore_v1_kvstore_proto_goTypes = nil
	file_nitric_proto_kvstore_v1_kvstore_proto_depIdxs = nil
}
