---
project_name: awstf
release:
  prerelease: auto
before:
  hooks:
    - go work sync
    - make predeploybin
builds:
  - id: awstf
    env:
      - CGO_ENABLED=0 
    binary: aws
    main: ./cmd/deploytf
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
    id: awstf
    builds:
      - awstf
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "awstf_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
