// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: nitric/proto/keyvalue/v1/keyvalue.proto

package KeyValuepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeyValueClient is the client API for KeyValue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValueClient interface {
	// Get an existing value
	Get(ctx context.Context, in *KeyValueGetRequest, opts ...grpc.CallOption) (*KeyValueGetResponse, error)
	// Create a new or overwrite an existing value
	Set(ctx context.Context, in *KeyValueSetRequest, opts ...grpc.CallOption) (*KeyValueSetResponse, error)
	// Delete a key and its value
	Delete(ctx context.Context, in *KeyValueDeleteRequest, opts ...grpc.CallOption) (*KeyValueDeleteResponse, error)
	// Iterate over all keys in a store
	Keys(ctx context.Context, in *KeyValueKeysRequest, opts ...grpc.CallOption) (KeyValue_KeysClient, error)
}

type keyValueClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueClient(cc grpc.ClientConnInterface) KeyValueClient {
	return &keyValueClient{cc}
}

func (c *keyValueClient) Get(ctx context.Context, in *KeyValueGetRequest, opts ...grpc.CallOption) (*KeyValueGetResponse, error) {
	out := new(KeyValueGetResponse)
	err := c.cc.Invoke(ctx, "/nitric.proto.KeyValue.v1.KeyValue/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueClient) Set(ctx context.Context, in *KeyValueSetRequest, opts ...grpc.CallOption) (*KeyValueSetResponse, error) {
	out := new(KeyValueSetResponse)
	err := c.cc.Invoke(ctx, "/nitric.proto.KeyValue.v1.KeyValue/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueClient) Delete(ctx context.Context, in *KeyValueDeleteRequest, opts ...grpc.CallOption) (*KeyValueDeleteResponse, error) {
	out := new(KeyValueDeleteResponse)
	err := c.cc.Invoke(ctx, "/nitric.proto.KeyValue.v1.KeyValue/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueClient) Keys(ctx context.Context, in *KeyValueKeysRequest, opts ...grpc.CallOption) (KeyValue_KeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &KeyValue_ServiceDesc.Streams[0], "/nitric.proto.KeyValue.v1.KeyValue/Keys", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyValue_KeysClient interface {
	Recv() (*KeyValueKeysResponse, error)
	grpc.ClientStream
}

type keyValueKeysClient struct {
	grpc.ClientStream
}

func (x *keyValueKeysClient) Recv() (*KeyValueKeysResponse, error) {
	m := new(KeyValueKeysResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeyValueServer is the server API for KeyValue service.
// All implementations should embed UnimplementedKeyValueServer
// for forward compatibility
type KeyValueServer interface {
	// Get an existing value
	Get(context.Context, *KeyValueGetRequest) (*KeyValueGetResponse, error)
	// Create a new or overwrite an existing value
	Set(context.Context, *KeyValueSetRequest) (*KeyValueSetResponse, error)
	// Delete a key and its value
	Delete(context.Context, *KeyValueDeleteRequest) (*KeyValueDeleteResponse, error)
	// Iterate over all keys in a store
	Keys(*KeyValueKeysRequest, KeyValue_KeysServer) error
}

// UnimplementedKeyValueServer should be embedded to have forward compatible implementations.
type UnimplementedKeyValueServer struct {
}

func (UnimplementedKeyValueServer) Get(context.Context, *KeyValueGetRequest) (*KeyValueGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKeyValueServer) Set(context.Context, *KeyValueSetRequest) (*KeyValueSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedKeyValueServer) Delete(context.Context, *KeyValueDeleteRequest) (*KeyValueDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKeyValueServer) Keys(*KeyValueKeysRequest, KeyValue_KeysServer) error {
	return status.Errorf(codes.Unimplemented, "method Keys not implemented")
}

// UnsafeKeyValueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValueServer will
// result in compilation errors.
type UnsafeKeyValueServer interface {
	mustEmbedUnimplementedKeyValueServer()
}

func RegisterKeyValueServer(s grpc.ServiceRegistrar, srv KeyValueServer) {
	s.RegisterService(&KeyValue_ServiceDesc, srv)
}

func _KeyValue_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nitric.proto.KeyValue.v1.KeyValue/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServer).Get(ctx, req.(*KeyValueGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValue_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nitric.proto.KeyValue.v1.KeyValue/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServer).Set(ctx, req.(*KeyValueSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValue_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nitric.proto.KeyValue.v1.KeyValue/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServer).Delete(ctx, req.(*KeyValueDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValue_Keys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyValueKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServer).Keys(m, &keyValueKeysServer{stream})
}

type KeyValue_KeysServer interface {
	Send(*KeyValueKeysResponse) error
	grpc.ServerStream
}

type keyValueKeysServer struct {
	grpc.ServerStream
}

func (x *keyValueKeysServer) Send(m *KeyValueKeysResponse) error {
	return x.ServerStream.SendMsg(m)
}

// KeyValue_ServiceDesc is the grpc.ServiceDesc for KeyValue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nitric.proto.KeyValue.v1.KeyValue",
	HandlerType: (*KeyValueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KeyValue_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KeyValue_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KeyValue_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Keys",
			Handler:       _KeyValue_Keys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nitric/proto/keyvalue/v1/keyvalue.proto",
}
