run:
  timeout: "5m"
  go: 1.21

linters:
  disable-all: true
  enable:
  - goimports
  - gofmt
  - govet
  - gofumpt
  - whitespace
  - staticcheck
  - ineffassign
  - unused
  - misspell
  - unconvert
  - errcheck
  - errorlint

issues:
  exclude-files:
  - tools/tools.go
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  govet:
    check-shadowing: false
