name: publish-azuretf

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.0
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          args: release --clean -f .goreleaser.tf.yaml
          workdir: cloud/azure
          version: "~> v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
